export type HokmGameState =
  | "WAITING_FOR_PLAYERS"
  | "TEAM_SELECTION"
  | "READY_TO_START"
  | "SHUFFLING"
  | "DEAL_FIRST_FIVE"
  | "WAITING_FOR_HOKM"
  | "DEAL_REMAINING"
  | "PLAYING"
  | "COLLECTING_CARDS"
  | "ROUND_FINISHED"
  | "GAME_FINISHED";